# Generated by Django 4.0.4 on 2022-05-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('О', 'Однокомнатная'), ('Д', 'Двухкомнатная')], max_length=1)),
                ('max_person', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo_main', models.FileField(upload_to='apartments')),
                ('photo_main_little', models.FileField(upload_to='apartments')),
                ('photo_1', models.FileField(upload_to='apartments')),
                ('photo_2', models.FileField(upload_to='apartments')),
                ('photo_3', models.FileField(upload_to='apartments')),
                ('photo_4', models.FileField(upload_to='apartments')),
                ('photo_5', models.FileField(upload_to='apartments')),
                ('photo_6', models.FileField(upload_to='apartments')),
                ('googlemap_addres', models.CharField(max_length=10000)),
            ],
        ),
    ]
