# Generated by Django 4.0.4 on 2022-07-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suto_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='photo_10',
            field=models.FileField(blank=True, null=True, upload_to='apartments'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='photo_11',
            field=models.FileField(blank=True, null=True, upload_to='apartments'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='photo_12',
            field=models.FileField(blank=True, null=True, upload_to='apartments'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='photo_7',
            field=models.FileField(blank=True, null=True, upload_to='apartments'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='photo_8',
            field=models.FileField(blank=True, null=True, upload_to='apartments'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='photo_9',
            field=models.FileField(blank=True, null=True, upload_to='apartments'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('С', 'Свободный'), ('З', 'Занят')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='photo_1',
            field=models.FileField(blank=True, null=True, upload_to='apartments'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='photo_2',
            field=models.FileField(blank=True, null=True, upload_to='apartments'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='photo_3',
            field=models.FileField(blank=True, null=True, upload_to='apartments'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='photo_4',
            field=models.FileField(blank=True, null=True, upload_to='apartments'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='photo_5',
            field=models.FileField(blank=True, null=True, upload_to='apartments'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='photo_6',
            field=models.FileField(blank=True, null=True, upload_to='apartments'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='photo_main',
            field=models.FileField(blank=True, null=True, upload_to='apartments'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='photo_main_little',
            field=models.FileField(blank=True, null=True, upload_to='apartments'),
        ),
    ]
